// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxWiK403_fCag9haIJ5R0vOQ6Xwag1U70',
    appId: '1:773618770513:web:966312008bbbae1cfa4e70',
    messagingSenderId: '773618770513',
    projectId: 'personal-portfolio-websi-6a4dd',
    authDomain: 'personal-portfolio-websi-6a4dd.firebaseapp.com',
    storageBucket: 'personal-portfolio-websi-6a4dd.appspot.com',
    measurementId: 'G-R9YMW4GFHG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxWiK403_fCag9haIJ5R0vOQ6Xwag1U70',
    appId: '1:773618770513:web:c0a2f578ed14f315fa4e70',
    messagingSenderId: '773618770513',
    projectId: 'personal-portfolio-websi-6a4dd',
    authDomain: 'personal-portfolio-websi-6a4dd.firebaseapp.com',
    storageBucket: 'personal-portfolio-websi-6a4dd.appspot.com',
    measurementId: 'G-HX92NVPPWD',
  );
}
